import Foundation
import GRDB
import Testing
@testable import KodaCore

/// A broken fixture should fail once, here, with a clear reason — not as a dozen
/// confusing report failures that all look like bad SQL.
@Test func fixtureBuildsWithEveryTablePopulated() throws {
    let store = try ReportFixture.make()
    let counts = try store.dbQueue.read { db -> [String: Int] in
        var out: [String: Int] = [:]
        for table in ["urls", "responses", "page_facts", "links", "images", "hreflang"] {
            out[table] = try Int.fetchOne(db, sql: "SELECT count(*) FROM \(table)") ?? 0
        }
        return out
    }
    #expect(counts["urls"] == ReportFixture.pages.count + ReportFixture.external.count
                              + ReportFixture.images.count)
    for table in ["responses", "page_facts", "links", "images", "hreflang"] {
        #expect((counts[table] ?? 0) > 0, "\(table) is empty")
    }
}

/// Every path must be distinct, or `paths(_:_:)` silently collapses two rows into
/// one and a filter that returns both looks like it returned one.
@Test func fixturePathsAreUnique() {
    let all = (ReportFixture.pages + ReportFixture.external + ReportFixture.images).map(\.path)
    #expect(Set(all).count == all.count)
}

/// Redirect and canonical targets are resolved by path lookup, so a typo would
/// quietly become a NULL rather than an error.
@Test func fixtureRedirectAndCanonicalTargetsAllResolved() throws {
    let store = try ReportFixture.make()
    let unresolved = try store.dbQueue.read { db in
        try Int.fetchOne(db, sql: """
            SELECT count(*) FROM responses r
            JOIN urls u ON u.id = r.url_id
            WHERE u.path IN ('/redirect-301','/chain-1','/chain-2','/loop-a','/loop-b','/loop-self')
              AND r.redirect_target_id IS NULL
            """) ?? 0
    }
    #expect(unresolved == 0, "a redirect target path did not resolve")

    let badCanonical = try store.dbQueue.read { db in
        try Int.fetchOne(db, sql: """
            SELECT count(*) FROM page_facts f
            JOIN urls u ON u.id = f.url_id
            WHERE u.path IN ('/canonicalised','/canon-to-404') AND f.canonical_id IS NULL
            """) ?? 0
    }
    #expect(badCanonical == 0, "a canonical target path did not resolve")
}

/// The auto-generated defaults must stay unique, or pages that never opted into
/// a shared title silently become Duplicate findings and every count in the
/// Titles, Meta Description, and Headings reports is wrong.
@Test func fixtureAutoValuesAreUniquePerPage() {
    let paths = ReportFixture.pages.map(\.path)
    for make in [ReportFixture.autoTitle, ReportFixture.autoDesc, ReportFixture.autoH1] {
        let values = paths.map(make)
        #expect(Set(values).count == values.count)
    }
}


/// Links, images and hreflang entries are all resolved by path lookup, and an
/// unresolved endpoint is silently skipped. That is the right behaviour for the
/// builder and a trap for the fixture author: a typo'd path produces a link that
/// simply does not exist, and the report test that depended on it fails for a
/// reason nowhere near the typo. Caught once, here.
@Test func fixtureLinkEndpointsAllResolve() throws {
    let store = try ReportFixture.make()
    let known = Set((ReportFixture.pages + ReportFixture.external + ReportFixture.images)
        .map(\.path))
    let counts = try store.dbQueue.read { db -> (links: Int, images: Int, hreflang: Int) in
        (try Int.fetchOne(db, sql: "SELECT count(*) FROM links") ?? 0,
         try Int.fetchOne(db, sql: "SELECT count(*) FROM images") ?? 0,
         try Int.fetchOne(db, sql: "SELECT count(*) FROM hreflang") ?? 0)
    }
    #expect(counts.links == 14, "6 plain links plus 8 anchor-text links")
    #expect(counts.images == 4)
    #expect(counts.hreflang == 11)
    #expect(known.contains("/anchor-many"))
}


/// `pad(_:to:)` pads but never truncates, so a page with a long path gets a long
/// auto title and a long auto H1 — which trips the Over 60 and H1-over-70
/// filters and makes that page a false positive in reports it has nothing to do
/// with. Any page whose auto values would exceed a threshold must set its own.
@Test func noAutoGeneratedTextTripsALengthFilter() {
    for page in ReportFixture.pages {
        if page.title == ReportFixture.auto {
            #expect(ReportFixture.autoTitle(page.path).count <= 60,
                    "\(page.path) auto title would be flagged as over 60")
            #expect(ReportFixture.autoTitle(page.path).count >= 30,
                    "\(page.path) auto title would be flagged as under 30")
        }
        if page.h1 == ReportFixture.auto {
            #expect(ReportFixture.autoH1(page.path).count <= 70,
                    "\(page.path) auto H1 would be flagged as over 70")
        }
        if page.desc == ReportFixture.auto {
            let n = ReportFixture.autoDesc(page.path).count
            #expect(n >= 70 && n <= 155, "\(page.path) auto description trips a length filter")
        }
    }
}
